name: Deploy Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    # concurrency: FIXME: setup concurrency!!!
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terafform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init

      - name: Plan Terraform
        run: terraform plan

      - name: Apply Terraform
        run: |
          mkfifo /tmp/tf-approve
          terraform apply < /tmp/tf-approve &
          sleep 10
          echo "no" > /tmp/tf-approve
          rm /tmp/tf-approve
